; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32-s3-devkitc-1

[env:esp32-s3-devkitc-1]
platform = espressif32@^6.0.0
board = esp32-s3-devkitc-1
framework = arduino
lib_deps =
	teemuatlut/TMCStepper@^0.7.3
	gin66/FastAccelStepper@^0.33.9
	bblanchon/ArduinoJson@^7.0.0
	me-no-dev/ESPAsyncWebServer@^3.0.0
	me-no-dev/AsyncTCP@^1.1.1
	marvinroger/AsyncMqttClient@^0.9.0
	adafruit/Adafruit SSD1306@^2.5.0
	adafruit/Adafruit GFX Library@^1.11.0
monitor_speed = 115200
build_flags =
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-UCONFIG_ESP_TASK_WDT_TIMEOUT_S
	-DCONFIG_ESP_TASK_WDT_TIMEOUT_S=120

[env:native]
platform = native
build_flags =
	-DUNIT_TEST
	-DARDUINOJSON_ENABLE_ARDUINO_STRING=1
	-DARDUINOJSON_ENABLE_ARDUINO_PRINT=0
	-DARDUINOJSON_ENABLE_PROGMEM=0
	-DARDUINOJSON_ENABLE_ARDUINO_STREAM=0
	-std=c++17
	-I test/native/mocks
	-I src
lib_deps =
	bblanchon/ArduinoJson@^7.0.0
build_src_filter =
	+<../test/native/mock_src/>
test_filter = native/*
test_build_src = yes